// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egnetlqsgdudszrxhppq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnbmV0bHFzZ2R1ZHN6cnhocHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDQyMTAsImV4cCI6MjA2ODI4MDIxMH0.uM649bo0mdek7smGCa-qS38EShiLu2m4G2M1rGRxwhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});